name: Build

on:
  push:
    branches:
      - master
  release:
    types:
      - created
  workflow_dispatch:
    inputs:
      version:
        description: "バージョン情報 (A.BB.C / A.BB.C-preview.D)"
        required: true
      prerelease:
        description: "プレリリースかどうか"
        type: boolean
        default: true
      code_signing:
        description: "コード署名する"
        type: boolean
        default: false
      upload_artifact:
        description: "デバッグ用に成果物を artifact にアップロードするか"
        type: boolean
        default: false

env:
  AIVISSPEECH_ENGINE_VERSION: "0.2.0"
  AIVISSPEECH_EDITOR_VERSION:
    |- # releaseタグ名か、workflow_dispatchでのバージョン名か、999.999.999-developが入る
    ${{ github.event.release.tag_name || github.event.inputs.version || '999.999.999-develop' }}

defaults:
  run:
    shell: bash

jobs:
  build-and-upload:
    environment: ${{ github.event.inputs.code_signing == 'true' && 'code_signing' || '' }} # コード署名用のenvironment（false時の挙動は2022年7月10日時点で未定義動作）
    env:
      ELECTRON_CACHE: .cache/electron
      ELECTRON_BUILDER_CACHE: .cache/electron-builder
      cache-version: v2
      # GNUコマンド
      sed: ${{ startsWith(matrix.os, 'macos-') && 'gsed' || 'sed' }}
      # ref: https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/vite/
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        artifact_name:
          - windows-x64-prepackage
        include:
          # Windows x64
          - artifact_name: windows-x64-prepackage
            artifact_path: dist_electron/win-unpacked
            aivisspeech_engine_asset_name: Windows-x64
            package_name: DaisukiTTS
            compressed_artifact_name: DaisukiTTS-Windows-x64
            app_asar_dir: prepackage/resources
            installer_artifact_name: windows-x64-nsis-web
            nsis_web_artifact_name: "DaisukiTTS-Windows-x64-${version}.${ext}"
            os: windows-2022

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set release version
        id: set_version
        run: |
          echo "RELEASE_VERSION=${{ github.event.release.tag_name || github.event.inputs.version || github.sha }}" >> $GITHUB_ENV


      # Rename executable file
      # NOTE: If the CPU/DirectML/GPU builds have the same package name,
      #       the NSIS installers and the 7z files have duplicate names.
      #       For Linux, If they have the same product name,
      #       the AppImages have duplicate names.
      #       Files with the same name cannot be uploaded to a single GitHub Release,
      #       so different package/product names should be used for CPU/DirectML/GPU builds.
      - name: Replace package name & version
        run: |
          $sed -i 's/"name": "DaisukiTTS"/"name": "${{ matrix.package_name }}"/' package.json

          $sed -i 's/"version": "999.999.999"/"version": "${{ env.AIVISSPEECH_EDITOR_VERSION }}"/' package.json

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: Cache Electron
        uses: actions/cache@v4
        with:
          path: ${{ env.ELECTRON_CACHE }}
          key: ${{ env.cache-version }}-${{ runner.os }}--electron-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ env.cache-version }}-${{ runner.os }}--electron-cache-

      - name: Cache Electron-Builder
        uses: actions/cache@v4
        with:
          path: ${{ env.ELECTRON_BUILDER_CACHE }}
          key: ${{ env.cache-version }}-${{ runner.os }}--electron-builder-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ env.cache-version }}-${{ runner.os }}--electron-builder-cache-

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Overwrite .env.production for macOS
        if: startsWith(matrix.os, 'macos-')
        run: |
          $sed -i 's|DaisukiTTS-Engine/run.exe|../Resources/DaisukiTTS-Engine/run|g' .env.production

      - name: Generate public/licenses.json
        run: pnpm run license:generate

      - name: Define Code Signing Envs
        if: startsWith(matrix.os, 'windows-') && github.event.inputs.code_signing == 'true'
        run: |
          bash tools/codesign_setup.bash
          THUMBPRINT="$(head -n 1 $THUMBPRINT_PATH)"
          SIGNTOOL_PATH="$(head -n 1 $SIGNTOOL_PATH_PATH)"
          echo "::add-mask::$THUMBPRINT"

          echo "WIN_CERTIFICATE_SHA1=$THUMBPRINT" >> $GITHUB_ENV
          echo 'WIN_SIGNING_HASH_ALGORITHMS=["sha256"]' >> $GITHUB_ENV
          echo "SIGNTOOL_PATH=$SIGNTOOL_PATH" >> $GITHUB_ENV
        env:
          ESIGNERCKA_USERNAME: ${{ secrets.ESIGNERCKA_USERNAME }}
          ESIGNERCKA_PASSWORD: ${{ secrets.ESIGNERCKA_PASSWORD }}
          ESIGNERCKA_TOTP_SECRET: ${{ secrets.ESIGNERCKA_TOTP_SECRET }}
          THUMBPRINT_PATH: /tmp/esignercka_thumbprint.txt
          SIGNTOOL_PATH_PATH: /tmp/signtool_path.txt

      # Build result will be exported to ${{ matrix.artifact_path }}
      - name: Build Electron
        env:
          NSIS_WEB_ARTIFACT_NAME: ${{ matrix.nsis_web_artifact_name }}
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}

          # https://github.com/electron-userland/electron-builder/issues/3179
          USE_HARD_LINKS: false
        run: pnpm run electron:build --dir

      - name: Reset Code Signing Envs
        if: startsWith(matrix.os, 'windows-') && github.event.inputs.code_signing == 'true'
        run: |
          bash tools/codesign_cleanup.bash
          echo 'WIN_CERTIFICATE_SHA1=' >> $GITHUB_ENV
          echo 'WIN_SIGNING_HASH_ALGORITHMS=' >> $GITHUB_ENV
          echo 'SIGNTOOL_PATH=' >> $GITHUB_ENV
        env:
          THUMBPRINT_PATH: /tmp/esignercka_thumbprint.txt

      - name: Rename NoEngine Prepackage
        run: |
          mv ${{ matrix.artifact_path }} ./prepackage

      # Download DaisukiTTS Engine
      - name: Download DaisukiTTS Engine
        id: download-engine
        uses: ./.github/actions/download-engine
        with:
          version: ${{ env.AIVISSPEECH_ENGINE_VERSION }}
          dest: ${{ github.workspace }}/DaisukiTTS-Engine
          target: ${{ matrix.aivisspeech_engine_asset_name }}
          token: ${{ secrets.ENGINE_DOWNLOADER_TOKEN }}

      - name: Merge DaisukiTTS Engine into prepackage/
        if: startsWith(matrix.artifact_name, 'windows-') || startsWith(matrix.artifact_name, 'linux-')
        run: |
          mv DaisukiTTS-Engine/ prepackage/DaisukiTTS-Engine/

      - name: Create Windows & Mac zip (without nvidia)
        if: (startsWith(matrix.artifact_name, 'windows-') || startsWith(matrix.artifact_name, 'macos-')) && !contains(matrix.artifact_name, 'nvidia')
        run: |
          name="${{ matrix.compressed_artifact_name }}-${{ env.AIVISSPEECH_EDITOR_VERSION }}"
          7z a -tzip $name.zip prepackage/
          7z rn $name.zip prepackage/ DaisukiTTS/

      - name: Upload Windows & Mac zip (without nvidia) to Artifacts
        if: (startsWith(matrix.artifact_name, 'windows-') || startsWith(matrix.artifact_name, 'macos-')) && !contains(matrix.artifact_name, 'nvidia') && github.event.inputs.upload_artifact == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}-zip
          path: |-
            ${{ matrix.compressed_artifact_name }}-${{ env.AIVISSPEECH_EDITOR_VERSION }}.zip

      - name: Upload Windows & Mac zip (without nvidia) to Release Assets
        if: (startsWith(matrix.artifact_name, 'windows-') || startsWith(matrix.artifact_name, 'macos-')) && !contains(matrix.artifact_name, 'nvidia') && (github.event.release.tag_name || github.event.inputs.version) != ''
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ github.event.inputs.prerelease }}
          tag_name: ${{ env.AIVISSPEECH_EDITOR_VERSION }}
          files: |-
            ${{ matrix.compressed_artifact_name }}-${{ env.AIVISSPEECH_EDITOR_VERSION }}.zip
          target_commitish: ${{ github.sha }}

      - name: Delete Windows & Mac zip (without nvidia)
        if: (startsWith(matrix.artifact_name, 'windows-') || startsWith(matrix.artifact_name, 'macos-')) && !contains(matrix.artifact_name, 'nvidia')
        run: |
          rm ${{ matrix.compressed_artifact_name }}-${{ env.AIVISSPEECH_EDITOR_VERSION }}.zip

      - name: Define Code Signing Envs
        if: startsWith(matrix.os, 'windows-') && github.event.inputs.code_signing == 'true'
        run: |
          bash tools/codesign_setup.bash
          THUMBPRINT="$(head -n 1 $THUMBPRINT_PATH)"
          SIGNTOOL_PATH="$(head -n 1 $SIGNTOOL_PATH_PATH)"
          echo "::add-mask::$THUMBPRINT"

          echo "WIN_CERTIFICATE_SHA1=$THUMBPRINT" >> $GITHUB_ENV
          echo 'WIN_SIGNING_HASH_ALGORITHMS=["sha256"]' >> $GITHUB_ENV
          echo "SIGNTOOL_PATH=$SIGNTOOL_PATH" >> $GITHUB_ENV
        env:
          ESIGNERCKA_USERNAME: ${{ secrets.ESIGNERCKA_USERNAME }}
          ESIGNERCKA_PASSWORD: ${{ secrets.ESIGNERCKA_PASSWORD }}
          ESIGNERCKA_TOTP_SECRET: ${{ secrets.ESIGNERCKA_TOTP_SECRET }}
          THUMBPRINT_PATH: /tmp/esignercka_thumbprint.txt
          SIGNTOOL_PATH_PATH: /tmp/signtool_path.txt

      # NOTE: prepackage can be removed before splitting nsis-web archive
      - name: Build Electron
        if: endsWith(matrix.installer_artifact_name, '-nsis-web') || endsWith(matrix.installer_artifact_name, '-appimage') # windows and linux
        env:
          NSIS_WEB_ARTIFACT_NAME: ${{ matrix.nsis_web_artifact_name }}
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
        run: |
          pnpm run electron:build --prepackaged prepackage/

      - name: Reset Code Signing Envs
        if: startsWith(matrix.os, 'windows-') && github.event.inputs.code_signing == 'true'
        run: |
          bash tools/codesign_cleanup.bash
          echo 'WIN_CERTIFICATE_SHA1=' >> $GITHUB_ENV
          echo 'WIN_SIGNING_HASH_ALGORITHMS=' >> $GITHUB_ENV
          echo 'SIGNTOOL_PATH=' >> $GITHUB_ENV
        env:
          THUMBPRINT_PATH: /tmp/esignercka_thumbprint.txt

      - name: Upload Windows NSIS Web to Artifacts
        if: endsWith(matrix.installer_artifact_name, '-nsis-web') && github.event.inputs.upload_artifact == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.installer_artifact_name }}-release
          path: |-
            dist_electron/nsis-web/out/*.7z.*
            dist_electron/nsis-web/*.exe

      - name: Upload Windows NSIS Web to Release Assets
        if: endsWith(matrix.installer_artifact_name, '-nsis-web') && (github.event.release.tag_name || github.event.inputs.version) != ''
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ github.event.inputs.prerelease }}
          tag_name: ${{ env.AIVISSPEECH_EDITOR_VERSION }}
          files: |-
            dist_electron/nsis-web/out/*.7z.*
            dist_electron/nsis-web/*.exe
          target_commitish: ${{ github.sha }}

  update-tag-to-current-commit:
    if: ${{ (github.event.release.tag_name || github.event.inputs.version) != '' }}
    needs: [build-and-upload]
    runs-on: ubuntu-latest
    steps:
      - name: <Setup> Check out the repository
        uses: actions/checkout@v4

      - name: <Deploy> Change tag to this commit for refreshing the release # c.f. voicevox_engine#854
        run: |
          git tag -f ${{ github.event.release.tag_name || github.event.inputs.version }}
          git push -f --tag
